sonar.projectKey=martineez99_qacloud-qa-project
sonar.organization=martineez99

sonar.projectName=QA Cloud - Test Automation Suite
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.exclusions=node_modules/**,dist/**,reports/**,.auth/**,src/performance/**

sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8